#!/bin/sh

## hyphop ##

#= prerape rescue image for sd/usb/mmc disk - vfat

## usage ./prapare_sd_image_rescue [ /dev/FLASHDISK ] | [ @remote_host ]

DEV="$1"

sudo=sudo

REBUILD_RESCUE=

case "$@" in
    -r)
    REBUILD_RESCUE=1
    ;;
    *@*)
    DEV="$1"
    ;;
    *)
    [ -b "$1" ] && {
	DEV="$1"
    }
    ;;
esac

## rebuild rescue image

[ "$REBUILD_RESCUE" ] && {
    $(dirname $0)/pack_image -r
}

D=/tmp/krescue.sd

[ -d $D ] || mkdir $D

UBOOT_SD=../share/u-boot.sd.bin

[ -f $UBOOT_SD ] || {
    echo "[e] not found $UBOOT_SD">&2
    exit 1
}

P=$PWD

DD=$D.img

OF=3276 ## 1.6M before

S=$((14*1024*1024))
BS=512

CMD(){
    echo "[#] $@">&2
    "$@"
}

CMD dd if=/dev/zero count=$((S/$BS + $OF)) bs=$BS of=$DD
CMD dd if=$UBOOT_SD bs=$BS conv=notrunc of=$DD
printf "n\np\n1\n$OF\n\nw\nq\n" | fdisk $DD
CMD dd if=$UBOOT_SD  bs=444 count=1 conv=notrunc of=$DD

LOOP=$($sudo losetup -f)

CMD $sudo losetup -o $((OF*$BS)) $LOOP $DD
CMD $sudo mkfs.vfat -n rescue $LOOP
CMD $sudo mount -o user,uid=$(id -u),gid=$(id -g) $LOOP $D

RESCUE=/rescue

[ -d $D$RESCUE ] || mkdir -p $D$RESCUE

CMD cp ../docs/README-rescue.md $D/README.TXT
CMD cp ../share/uI* $D$RESCUE
CMD cp ../share/linux.dtb $D$RESCUE/uboot.dtb
CMD cp ../share/splash.bmp.gz $D$RESCUE
CMD cp ../files/boot.sd.cmd $D$RESCUE
CMD cp ../files/80_user_env.txt $D$RESCUE

ls -l1 $D/* | tee $D$RESCUE/files.list
md5sum $D/$RESCUE/* > $D$RESCUE/files.md5sum
echo "$(date)" > $D$RESCUE/generated.date

CMD sync

CMD $sudo losetup -d $LOOP || {
    echo "[i] loop $LOOP still used">&2
}

echo "[i] rescue sd image: $DD is ready">&2

ls -Ll1 $DD

gzip -c $DD > $DD.gz

ls -Ll1 $DD.gz

[ -b "$DEV" ] && {

#    echo "[i] type Y for allow write to $DEV">&2
#    [ "$(read YES)" = "Y" ] || {
#	echo "[w] owe wait only Y not $YES">&2
#	exit 1
#    }

    echo "[i] write image $DD -> $DEV flash disk! plz wait...">&2
    CMD $sudo dd if=$DD of=$DEV conv=notrunc bs=8192
    CMD sync
    echo "[i] DONE">&2

    exit
}

case $DEV in
    *@*)
    TO="root@${DEV#*@}"
    echo "[i] remote ssh write image $DD to sd">&2
    CMD ssh $TO dd of=/dev/mmcblk1 conv=sync bs=4096 < $DD
    echo "[i] DONE">&2
    exit
    ;;
esac

echo "[i] maybe next command for write it">&2
echo "./image2flash /tmp/krescue.upgrade.disk.img /dev/#your_drive " >&2
echo "# or remote write to sd">&2
echo "ssh root@vimu dd of=/dev/mmcblk1 bs=4096 < /tmp/krescue.spi.bin">&2


