#!/bin/sh

set -e

## hyphop ##

#= prerape rescue image for sd/usb/mmc disk - vfat - uboots 

## usage ./prapare_sd_image_rescue [-r] [ /dev/FLASHDISK ] | [ @remote_host ]

DEV="$1"

sudo=sudo

REBUILD_RESCUE=

DEV2=/dev/mmcblk1

UBOOT_VER=

for a in "$@"; do
case $a in
    -r)
    REBUILD_RESCUE=1
    ;;
    -1)
UBOOT_VER=1
    ;;
    -2)
UBOOT_VER=2
    ;;
    -3)
UBOOT_VER=3
    ;;
    *@*)
    DEV="$a"
    ;;
    /dev/mmc*)
    DEV2=$a
    ;;
    *)
    [ -b "$a" ] && {
	DEV="$a"
    }
    ;;
esac
done


## rebuild rescue image

[ "$REBUILD_RESCUE" ] && {
    $(dirname $0)/pack_image -r
}

CMD(){
    echo "[#] $@">&2
    "$@"
}

D=/tmp/krescue.sd

grep $D /proc/mounts && CMD $sudo umount $D
CMD $sudo losetup -D

[ -d $D ] || mkdir $D

UBOOT_SD=../share/u-boot.sd.bin
UBOOT_SPI=../share/u-boot.spi.bin


#u-boot.sd.bin
#u-boot.vim1.sd.bin

[ "$UBOOT_VER" ] && {

    echo "[i] change uboot version to $UBOOT_VER">&2

    CMD ln -sf u-boot.vim$UBOOT_VER.sd.bin $UBOOT_SD
    CMD ln -sf u-boot.vim$UBOOT_VER.spi.bin $UBOOT_SPI

}

[ -f $UBOOT_SD ] || {
    echo "[e] not found $UBOOT_SD">&2
    exit 1
}

P=$PWD

DD=$D.img

OF=3276 ## 1.6M before

S=$((36*1024*1024))
S=$((52*1024*1024))
BS=512


CMD dd if=/dev/zero count=$((S/$BS + $OF)) bs=$BS of=$DD
CMD dd if=$UBOOT_SD bs=$BS conv=notrunc of=$DD
printf "n\np\n1\n$OF\n\nw\nq\n" | fdisk $DD
CMD dd if=$UBOOT_SD  bs=444 count=1 conv=notrunc of=$DD

LOOP=$($sudo losetup -f)

CMD $sudo losetup -o $((OF*$BS)) $LOOP $DD
CMD $sudo mkfs.vfat -n rescue $LOOP
CMD $sudo mount -o user,uid=$(id -u),gid=$(id -g) $LOOP $D

RESCUE=/rescue

[ -d $D$RESCUE ] || mkdir -p $D$RESCUE
[ -d $D$RESCUE/docs ] || mkdir -p $D$RESCUE/docs

CMD cp -L ../docs/README-rescue.md $D
CMD cp -L ../docs/README-rescue* $D$RESCUE/docs
CMD cp -L ../share/Image $D$RESCUE
CMD cp -L ../share/uInitrd* $D$RESCUE
CMD cp -L ../share/uImage* $D$RESCUE
CMD cp -L ../share/kvim3_linux.dtb $D$RESCUE/uboot.dtb
#CMD cp -L ../share/linux.dtb $D$RESCUE/linux.dtb
for f in ../share/*.dtb; do
    [ -f "$f" ] && {
	CMD cp -L $f $D$RESCUE
    }
done

CMD cp -L ../share/splash.bmp.gz $D$RESCUE
#CMD cp ../files/*_env.txt $D$RESCUE
CMD cp -L ../share/*_env.txt $D$RESCUE

CMD cp -L ../files/rescue.cmd $D$RESCUE
CMD cp -L ../files/cmd2scr $D$RESCUE

../files/cmd2scr $D$RESCUE/rescue.cmd

CMD cp $D$RESCUE/rescue.cmd $D$RESCUE/hook.cmd
CMD cp $D$RESCUE/rescue.scr $D$RESCUE/hook.scr
#//// need to ask about this
CMD cp $D$RESCUE/rescue.cmd $D/boot.ini
CMD cp $D$RESCUE/rescue.scr $D/boot.scr.uimg
CMD cp $D$RESCUE/rescue.scr $D/boot.scr.uimg
CMD cp $D$RESCUE/rescue.scr $D/s905_autoscript


for v in vim3 vim2 vim1; do
for t in sd spi; do

for s in /tmp ../bin; do

U="$s/uboot_$v/u-boot.$t.bin"

[ -f "$U" ] && {
    CMD cp "$U" "$D$RESCUE/u-boot.$v.$t.bin"
    break
}

done
done
done


[ -f /tmp/krescue.spi.bin ] && {
CMD cp /tmp/krescue.spi.bin $D$RESCUE/
}


SS=$D$RESCUE/scripts
[ -d $SS ] || CMD mkdir -p $SS
CMD cp ../scripts/sd/* $SS

ls -l1 $D/* | tee $D$RESCUE/files.list

#md5sum $D/$RESCUE/* > $D$RESCUE/files.md5sum

echo "$(date)" > $D$RESCUE/generated.date

CMD sync

[ "$TAR" ] && {
    CMD tar -czf $D.tar.gz -C$D .
}

CMD $sudo umount $D

CMD $sudo fsck.fat $LOOP

#CMD $sudo losetup -d $LOOP || {
CMD $sudo losetup -D || {
    echo "[i] loop $LOOP still used">&2
}

md5sum $DD | tee $DD.md5sum

echo "[i] rescue sd image: $DD is ready">&2

ls -Ll1 $DD

[ "$GZ" ] && {
    gzip -c $DD > $DD.gz
    ls -Ll1 $DD.gz
}
echo "[i] maybe write to $DEV">&2

[ -b "$DEV" ] && {

#    echo "[i] type Y for allow write to $DEV">&2
#    [ "$(read YES)" = "Y" ] || {
#	echo "[w] owe wait only Y not $YES">&2
#	exit 1
#    }

    echo "[i] write image $DD -> $DEV flash disk! plz wait...">&2
    CMD $sudo dd if=$DD of=$DEV conv=notrunc bs=8192
    CMD sync
    echo "[i] DONE">&2

    exit
}

### !!!! rebuild

case $DEV in
    *@*)
    TO="root@${DEV#*@}"
    echo "[i] remote ssh write image $DD to sd: $DEV2">&2
    CMD rsync -av --inplace $DD $TO:$DD && {
	echo "
	/opt/sd_boot $DD
	exit 
        " | CMD ssh $TO

    }
#
#    CMD ssh $TO dd of=$DEV2 conv=sync < $DD
    echo "[i] DONE">&2
    exit
    ;;
esac

echo "[i] maybe next command for write it">&2
echo "./image2flash /tmp/krescue.upgrade.disk.img /dev/#your_drive " >&2
echo "# or remote write to sd">&2
echo "ssh root@vimu dd of=/dev/mmcblk1 bs=4096 < /tmp/krescue.spi.bin">&2

