#!/bin/sh

## hyphop ##

#= simple console image writer

#IN=
#SD=

for a in "$@"; do
    [ -b "$a" ] && {
	SD="$a"
    }
    [ -f "$a" ] && {
	IN="$a"
    }
done

for t in /sys/class/block/*/device/model; do
    [ -f $t ] && {
    d=${t#*block/}
    d=${d%%/*}
    egrep -q "Card Reader" $t && {
    SD=/dev/$d
    echo "[i] auto detected dev: $SD ($(cat $t))">&2
    break
    }
    }
done

[ "$SD" ] || {
    echo "[e] target device not defined">&2
    exit 1
}

#echo "[i] burn image to $SD">&2

[ -b $SD ] || {
    echo "[e] not block dev $SD">&2
    exit 1
}

[ "$IN" ] || {
for i in *.zip; do
    [ -f "$i" ] && {
	IN="$i"
	break
    }
done
}

[ -f $IN ] || {
    echo "[e] not found image $IN">&2
    exit 1
}

echo "[i] IMAGE: $IN > $SD">&2

unzip -p "$IN" "*.img" | sudo dd bs=1M of=$SD

